version: '1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=AlgoCrack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=32865417
    ports:
      - "6432:5432"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway-service:
    build: ./api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  problem-service:
    build: ./problem-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: